@base_url = http://localhost:8080/api

### Should Update Deck

PUT {{base_url}}/deck/1
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "Updated Deck",
"dateCreated": "2026-08-27",
"dateUpdated": "2026-08-27"
}

### Should NOT Update Deck Where Deck IDs Do Not Match

PUT {{base_url}}/deck/2
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "Updated Deck",
"dateCreated": "2026-08-27",
"dateUpdated": "2026-08-27"
}

### Should NOT Update Deck Where Deck Does Not Exist

PUT {{base_url}}/deck/2147483647
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 2147483647,
"name": "Updated Deck",
"dateCreated": "2026-08-27",
"dateUpdated": "2026-08-27"
}

### Should NOT Update Deck Where Date Updated Is In The Past

PUT {{base_url}}/deck/1
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "Updated Deck",
"dateCreated": "2026-08-27",
"dateUpdated": "1990-12-01"
}

### Should NOT Update Deck Where Date Created Is Blank

PUT {{base_url}}/deck/1
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "Updated Deck",
"dateCreated": null,
"dateUpdated": "2026-08-27"
}

### Bad Path updatedDate is blank

PUT {{base_url}}/deck/1
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "Updated Deck",
"dateCreated": "2026-08-27",
"dateUpdated": null
}

### Bad Path name is blank

PUT {{base_url}}/deck/1
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "",
"dateCreated": "2026-08-27",
"dateUpdated": "2026-08-27"
}

### Add Card to Deck

### Happy Path
PUT {{base_url}}/deck/1/card/cultivate
Content-Type: application/json
authorization: {"id": "1","email": "c@c.com"}

{
"deckId": 1,
"name": "My Best Deck",
"dateCreated": "2026-08-28",
"dateUpdated": "2026-08-28"
}

### Bad Path Deck IDs don't match
PUT {{base_url}}/deck/999/card/black lotus
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "My Best Deck",
"dateCreated": "2026-08-28",
"dateUpdated": "2026-08-28"
}

### Bad Path dates are in past
PUT {{base_url}}/deck/1/card/black lotus
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "My Best Deck",
"dateCreated": "2026-08-20",
"dateUpdated": "2026-08-20"
}

### Bad Path deck name is blank
PUT {{base_url}}/deck/1/card/black lotus
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "",
"dateCreated": "2026-08-28",
"dateUpdated": "2026-08-28"
}