@base_url = http://localhost:8080/api

### Should Update Deck

PUT {{base_url}}/deck/1
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "Updated Deck",
"dateCreated": "2026-08-27",
"dateUpdated": "2026-08-27"
}

### Should NOT Update Deck Where Deck IDs Do Not Match

PUT {{base_url}}/deck/2
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "Updated Deck",
"dateCreated": "2026-08-27",
"dateUpdated": "2026-08-27"
}

### Should NOT Update Deck Where Deck Does Not Exist

PUT {{base_url}}/deck/2147483647
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 2147483647,
"name": "Updated Deck",
"dateCreated": "2026-08-27",
"dateUpdated": "2026-08-27"
}

### Should NOT Update Deck Where Date Updated Is In The Past

PUT {{base_url}}/deck/1
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "Updated Deck",
"dateCreated": "2026-08-27",
"dateUpdated": "1990-12-01"
}

### Should NOT Update Deck Where Date Created Is Blank

PUT {{base_url}}/deck/1
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "Updated Deck",
"dateCreated": null,
"dateUpdated": "2026-08-27"
}

### Bad Path updatedDate is blank

PUT {{base_url}}/deck/1
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "Updated Deck",
"dateCreated": "2026-08-27",
"dateUpdated": null
}

### Bad Path name is blank

PUT {{base_url}}/deck/1
Content-Type: application/json
authorization: {"id": "1","email": "[a@a.com](mailto:a@a.com)"}

{
"deckId": 1,
"name": "",
"dateCreated": "2026-08-27",
"dateUpdated": "2026-08-27"
}

### Update Card Quantity - Happy Path (204 No Content)
PUT {{base_url}}/deck/1/card/10 HTTP/1.1
Content-Type: application/json
authorization: {"id": "1", "email": "a@a.com"}

{
  "quantity": 4
}

### Update Card Quantity - Bad Path: Deck or Card Not Found (404 Not Found)
PUT {{base_url}}/deck/999999/card/10 HTTP/1.1
Content-Type: application/json
authorization: {"id": "1", "email": "a@a.com"}

{
  "quantity": 4
}

### Update Card Quantity - Bad Path: Invalid Quantity / Transaction Error (400 Bad Request)
PUT {{base_url}}/deck/1/card/10 HTTP/1.1
Content-Type: application/json
authorization: {"id": "1", "email": "a@a.com"}

{
  "quantity": -1
}

### Update Card Quantity - Bad Path: Missing authorization header (400 Bad Request)
PUT {{base_url}}/deck/1/card/10 HTTP/1.1
Content-Type: application/json

{
  "quantity": 4
}