@base_url = http://localhost:8080/api/collection

### GET All cards from collection

### Bad Request missing Auth Header
GET {{base_url}} HTTP/1.1

### Good Request
GET {{base_url}} HTTP/1.1
Authorization: { "id": "1","email": "c@c.com"}
